apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fist-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: first-nginx.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-app-service
                port:
                  number: 6000
